#!/bin/bash

sudo apt-get -y install apache2
sudo add-apt-repository -y ppa:ondrej/php5
sudo apt-get update
sudo apt-get -y install php5 libapache2-mod-php5
sudo apt-get -y install php5-mcrypt
sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password password '
sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password '
sudo apt-get -y install mysql-server
sudo apt-get -y install php5-mysql
sudo apt-get -y  install git-core
cd /var/www/html
sudo rm -r *
sudo git clone https://github.com/VedranBrnjetic/recipe.git .
sudo chmod -R 777 ./
sudo chown www-data ./
sudo curl -sS https://getcomposer.org/installer | php
sudo php composer.phar install
echo "create database recipe" | mysql -u root
echo "grant all privileges on recipe.* to 'MasterChef'@'localhost' identified by 'g1vemethe1ngred1ents';" | mysql -u root
sudo php artisan key:generate
sudo php artisan migrate
sudo cp /var/www/html/env_config/apache2.conf /etc/apache2/apache2.conf
sudo cp /var/www/html/env_config/000-default.conf /etc/apache2/sites-available/000-default.conf
sudo a2enmod rewrite
sudo service apache2 restart
curl http://localhost/database
